version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      # - ./mongodb.conf:/etc/mongod.conf.orig
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
